## You can directly update with your own path
dataset:
  semi_supervised_labels_path: '../dataset/semisupervised_labels/Labels'
  planet_boxes_path: '../dataset/planet'
  planet_test_boxes_path: '../dataset/ai4eo/planet_test'
  sentinel_boxes_path: '../dataset/ai4eo/sentinel-2'
  sentinel_test_boxes_path: '../dataset/ai4eo/planet-2_test'
model-param:
  n_epochs: 10
  batch_size: 40
  n_classes: 8
results:
  save_model_path: 'weights/18-05-10epochs_INS'
